### ISSUE TITLE
Possible index error found in function implementation code

### ISSUE THREAD

**Issue by Upupdownn** [epifluidlab/FinaleToolkit#106]
**Location**
src/finaletoolkit/frag/end_motifs.py, line 610
function: region_end_motifs()
**content**
~~~python
if frag[3]: # is on forward strand or not
    # py2bit uses 0-based for start, 1-based for end
    # forward end-motif
~~~
**description**
frag_generator returns a tuple (contig, read_start, read_stop, mapq, read_on_plus) for each iteration. Should the index in the if statement here be [4]?

**Comment by jamesli124** [comment]
Issue fixed in FinaleToolkit 0.7.6
